WebApp/Controllers/ItensController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Model;
using Dal;
using System.Net;
using System.Data;
using System.Data.Entity;
using WebApp.EF_DataModels;
using Repository;
using System.Data.SqlClient;
using System.IO;

namespace WebApp.Controllers
{
    public class ItensController : Controller
    {
        // GET: Itens
        dalItens _db = new dalItens();
        DB_OS_SISTEMASEntities dbContext = new DB_OS_SISTEMASEntities();

        public ActionResult Index()
        {
            if (Session["NomeLogin"] != null)
            {
                var model = dbContext.TB_PROJETO_ITENS.Include(t => t.TB_DEPARTAMENTO).Include(t => t.TB_DESENVOLVEDORES).Include(t => t.TB_PROJETO_DESENVOLVIMENTO).Include(t => t.TB_STATUS_DESENVOLVIMENTO).Include(t => t.TB_TIPO_DESENVOLVIMENTO).Include(t => t.TB_PRIORIDADE_ITEM);

                return View(model.ToList());
            }
            else
            {
                return RedirectToAction("Logar", "Usuario");
            }
        }

        // GET: Itens/Details/5
        public ActionResult Details(int id)
        {
            if (Session["NomeLogin"] != null)
            {

                ViewBag.Departamento = new SelectList(dbContext.TB_DEPARTAMENTO, "ID_DEPARTAMENTO", "NOME");
                ViewBag.Desenvolvedor = new SelectList(dbContext.TB_DESENVOLVEDORES, "ID_DEV", "NOME_DESENVOLVEDOR");
                ViewBag.TipoDesenvolvimento = new SelectList(dbContext.TB_TIPO_DESENVOLVIMENTO, "ID_TIPO_DESENV", "DESCRICAO");
                ViewBag.Status = new SelectList(dbContext.TB_STATUS_DESENVOLVIMENTO, "ID_STATUS", "DESCRICAO");
                ViewBag.Prioridade = new SelectList(dbContext.TB_PRIORIDADE_ITEM, "ID", "PRIORIDADE_TIPO");

                var model = _db.pubBuscaItemPorId(id);

                return View(model);
            }
            else
            {
                return RedirectToAction("Logar", "Usuario");
            }
        }

        //GET: Detalhe dos itens finalizadas
        public ActionResult ItemFinalizadoDetalhe(int id)
        {
            if (Session["NomeLogin"] != null)
            {
                var model = _db.pubItensFinalizadosDetalhe(id);

                return View(model);
            }
            else
            {
                return RedirectToAction("Logar", "Usuario");
            }

        }

        // GET: Itens/Create
        public ActionResult Create(int id)
        {
            if (Session["NomeLogin"] != null)
            {
                //Aqui efetua a validação para que não deixe efetuar abertura de um item se o id da OS (Build) for igual a 0.
                if (id == 0)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                // Se não for, carrega as combos de preenchimento e a tela de cadastro do novo item.
                ViewBag.Departamento = new SelectList(dbContext.TB_DEPARTAMENTO, "ID_DEPARTAMENTO", "NOME");
                ViewBag.Desenvolvedor = new SelectList(dbContext.TB_DESENVOLVEDORES, "ID_DEV", "NOME_DESENVOLVEDOR");
                ViewBag.TipoDesenvolvimento = new SelectList(dbContext.TB_TIPO_DESENVOLVIMENTO, "ID_TIPO_DESENV", "DESCRICAO");
                ViewBag.Status = new SelectList(dbContext.TB_STATUS_DESENVOLVIMENTO, "ID_STATUS", "DESCRICAO");
                ViewBag.Prioridade = new SelectList(dbContext.TB_PRIORIDADE_ITEM, "ID", "PRIORIDADE_TIPO");

                var model = _db.pubRegistraIdNovoItem(id);

                return View(model); // Carrega em tela combos, id da OS(Build) e o nome do projeto.
            }
            else
            {
                return RedirectToAction("Logar", "Usuario");
            }
        }

        // POST: Itens/Create
        [HttpPost]
        public ActionResult Create(int id, modItens item)
        {
            if (Session["NomeLogin"] != null)
            {
                try
                {
                    //aqui, seta as variáveis para salvar/gravar um novo item atrelado a uma OS (Build).
                    item.idNmSolicitacao = id;
                    item.dtAbertura = DateTime.Now;
                    item.idUsuarioLogado = Session["NomeLogin"].ToString(); //<-- Utiliza o login do usuário para enviar e-mail de abertura.

                    //anexo de arquivo no sistema
                    int anexo = 0;

                    for (int i = 0; i < Request.Files.Count; i++)
                    {
                        HttpPostedFileBase arquivo = Request.Files[i];

                        if (arquivo.ContentLength > 0)
                        {
                            var uploadPath = Server.MapPath("~/Images_Anexos");
                            string caminhoArq = Path.Combine(@uploadPath, Path.GetFileName(arquivo.FileName));

                            arquivo.SaveAs(caminhoArq);
                            anexo++;
                        }
                    }

                    ViewData["Mensagem"] = String.Format("{0} arquivo salvo com sucesso.", anexo);

                    //Salva no banco de dados o novo item aberto.
                    _db.pubCadastraNovoItem(item);

                    //Monta corpo do e-mail para envio ao desenvolvedor, admins do sistema e usuário abertura.
                    string corpo_email = "<html><head><title>Sistema de OS</title></head>"
                                       + "<body><h2>Item Nº: <b style='color:blue;'>{0}</b></h2> Projeto: <b>{1}</b> - Versão: <b>{2}</b></br><br>"
                                       + "<h3><b style='color:red;'><p>Aviso de novo item</p></b></h3>"
                                       + "</br>"
                                       + "<ul><li><b>Solicitante:</b> <u>{3}</u> - <b>Departamento:</b> {4} </li>"
                                       + "</br>"
                                       + "<li><b>Prioridade:</b> {5} - <b>Desenvolvedor Responsável:</b> {6} </li>"
                                       + "</br></br>"
                                       + "<li><b>Descrição:</b> {7} </li>"
                                       + "</body></html>",
                    //designado = "<li><b>Data: </b>{0}<ul><li><b>Nome: </b>{1}</li></ul></li>", //<--- Ainda não está sendo utilizado.
                    corpo = string.Empty, //<--- Variável utilizada depois para concatenar o corpo do e-mail com os outros valores a serem preenchidos vindos do BD.
                    lst_hist = string.Empty,
                    lst_desi = string.Empty,
                    lst_prod = string.Empty;

                    //Cria variável que realiza consulta no banco, do último item criado para enviar e-mail.
                    //var resultado = "";//_db.pubConsultaItemParaEnvioEmail();

                    //Seta variáveis que serão utilizadas para o corpo do e-mail
                    var idItem = 0;
                    var projeto = string.Empty;
                    var versao = string.Empty;
                    var nomeSoli = string.Empty;
                    var depto = string.Empty;
                    var desc = string.Empty;
                    var prior = string.Empty;
                    var emailDesenv = string.Empty;
                    var emailReq = string.Empty;
                    var desenvolv = string.Empty;

                    //saída para o envio da mensagem
                    var msg = "E-mail enviado!";

                    //Busca cada campo a ser preenchido no envio de e-mail (carrega corpo_mail)
                    //foreach (var final in resultado)
                    //{
                    //    idItem = final.idItem; //incrementa as variáveis com os valores do select após save do item.
                    //    projeto = final.nomeProjeto;
                    //    versao = final.versao;
                    //    nomeSoli = final.solicitante;
                    //    depto = final.depto;
                    //    desc = final.desc;
                    //    prior = final.prioridade;
                    //    emailDesenv = final.emailDev;
                    //    emailReq = final.emailUser;
                    //    desenvolv = final.desenvolvedor;
                    //}

                    //concatena o corpo do e-mail com os valores das variáveis, conforme posição dos campos no texto html acima, exemplo: {0}, {1}, {2}...
                    corpo = string.Format(corpo_email, idItem, projeto, versao, nomeSoli, depto, prior, desenvolv, desc);

                    //chama a classe do repositório onde está setado o envio do e-mail.
                    var envia = new EnviaEmailRepository();

                    //utiliza o método de envio de e-mail e concate o corpo, texto, campos a serem utilizados para envio conforme montado acima
                    envia.MandaEmail(string.Concat(emailReq, ";", emailDesenv),
                    string.Concat("Projeto: ", projeto, " Versão: ", versao, " Item: [ ", idItem.ToString(), " ]", " - Aviso de novo item"), corpo, out msg);

                    //Após todo o processo, exibe mensagem em tela com número do item e que foi enviado ao desenvolvedor.
                    ViewBag.Mensagem = "Item Nº: " + idItem + " enviado para desenvolvimento!";

                    return ViewBag.Mensagem;
                }

                catch
                {
                    ViewBag.Departamento = new SelectList(dbContext.TB_DEPARTAMENTO, "ID_DEPARTAMENTO", "NOME");
                    ViewBag.Desenvolvedor = new SelectList(dbContext.TB_DESENVOLVEDORES, "ID_DEV", "NOME_DESENVOLVEDOR");
                    ViewBag.TipoDesenvolvimento = new SelectList(dbContext.TB_TIPO_DESENVOLVIMENTO, "ID_TIPO_DESENV", "DESCRICAO");
                    ViewBag.Status = new SelectList(dbContext.TB_STATUS_DESENVOLVIMENTO, "ID_STATUS", "DESCRICAO");

WebApp/Controllers/OsProjetosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Model;
using Dal;
using WebApp.EF_DataModels;

namespace WebApp.Controllers
{
    public class OsProjetosController : Controller
    {
        // GET: OsProjetos
        dalProjetoEmDesenvolvimento _db = new dalProjetoEmDesenvolvimento();
        private DB_OS_SISTEMASEntities dbContext = new DB_OS_SISTEMASEntities();

        public ActionResult Index()
        {
            if (Session["NomeLogin"] != null)
            {
                var model = _db.pubListaTodosOsDesenvolvimento();

                return View(model);
            }
            else
            {
                return RedirectToAction("Logar", "Usuario");
            }
        }

        //GET: Detalhes de itens por Ordem de serviço / Lista (Collection)
        public ActionResult Details(int id)
        {
            if (Session["NomeLogin"] != null)
            {

                var model = _db.pubListaItensAtreladosNaOrdemdeServico(id);

                return View(model);
            }
            else
            {
                return RedirectToAction("Logar", "Usuario");
            }
        }    

        // GET: OsProjetos/Create
        public ActionResult Create()
        {
            if (Session["NomeLogin"] != null)
            {
                ViewBag.Projeto = new SelectList(dbContext.TB_PROJETOS_SISTEMAS, "ID_PROJETO", "NOME_PROJETO");

                return View();
            }
            else
            {
                return RedirectToAction("Logar", "Usuario");
            }
        }

        // POST: OsProjetos/Create
        [HttpPost]
        public ActionResult Create(modProjetoEmDesenvolvimento ordemServico)
        {           
               if (ModelState.IsValid)
                {
                    try
                    {
                        ordemServico.dtCadastro = DateTime.Now;
                        _db.pubCadastraNovoProjeto(ordemServico);

                        return RedirectToAction("Index");
                    }
                    catch
                    {
                        ViewBag.Projeto = new SelectList(dbContext.TB_PROJETOS_SISTEMAS, "ID_PROJETO", "NOME_PROJETO", ordemServico.idProjeto);
                        return View(ordemServico);
                    }
                }
                return View();           
        }

        // GET: OsProjetos/Edit/5
        public ActionResult Edit(int id)
        {
            if (Session["NomeLogin"] != null)
            {
                ViewBag.Projeto = new SelectList(dbContext.TB_PROJETOS_SISTEMAS, "ID_PROJETO", "NOME_PROJETO");

                var model = _db.pubBuscaOsProjetoPorId(id);            

                return View(model);
            }
            else
            {
                return RedirectToAction("Logar", "Usuario");
            }
        }

        // POST: OsProjetos/Edit/5
        [HttpPost]
        public ActionResult Edit(int id,modProjetoEmDesenvolvimento ordemServico)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    ordemServico.idNmSolitacao = id;
                    ordemServico.idUsuarioLogado = Session["NomeLogin"].ToString();

                    _db.pubAtualizaFinalizaProjetoEmDesenvolvimento(ordemServico);

                    return RedirectToAction("Index");
                }
                catch
                {
                    ViewBag.Projeto = new SelectList(dbContext.TB_PROJETOS_SISTEMAS, "ID_PROJETO", "NOME_PROJETO", ordemServico.idProjeto);

                    return View(ordemServico);
                }
            }
            return View();
            
        }

        // GET: OsProjetos/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: OsProjetos/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult ListaItensDaOs(int id)
        {
            if (Session["NomeLogin"] != null)
            {
                var model = _db.pubListaItensAtreladosNaOrdemdeServico(id);              

                var combo = _db.pubComboListaProjetosEmDesenvolvimento().ToList();        

                ViewBag.ComboSeleciona = new SelectList(combo, "idNmSolitacao", "nomeProjeto");

                return View(model);
            }
            else
            {
                return RedirectToAction("Logar", "Usuario");
            }
        }

        //LISTA TODOS OS ITENS DE PROJETOS FINALIZADOS PARA VER DETALHES
        public ActionResult ListaItensDaOsFinalizada(int id)
        {
            if (Session["NomeLogin"] != null)
            {
                var model = _db.pubListaItensAtreladosNaOrdemdeServico(id);           

                return View(model);
            }
            else
            {
                return RedirectToAction("Logar", "Usuario");
            }
        }
    }
}

WebApp/Views/Itens/Create.cshtml
@model Model.modItens

@{
    ViewBag.Title = "Novo Item";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Create", "Itens", FormMethod.Post, new { @id="_AjaxForm", @enctype="multipart/form-data"}))
{
    @Html.AntiForgeryToken()

    <div class="row">
        <div class="x_panel">
            <h4>Novo Item</h4>
            <hr />
            <div class="x_content">
                <form class="form-horizontal form-label-left input_mask form-group has-feedback">

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        <div class="col-xs-4">
                            @Html.Label("Projeto", htmlAttributes: new { @class = "control-label" })
                            @Html.TextBoxFor(model => model.nomeProjeto, null, htmlAttributes : new { @class = "form-control", @disabled="disabled", @style="color:red; text-align: center; font:bold;" })
                            @Html.ValidationMessageFor(model => model.idNmSolicitacao, "", new { @class = "text-danger" })
                        </div>

                        <div class="col-xs-4">
                            @Html.LabelFor(model => model.NomeSolicitante, htmlAttributes: new { @class = "control-label" })
                            @Html.EditorFor(model => model.NomeSolicitante, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.NomeSolicitante, "", new { @class = "text-danger" })
                        </div>

                        <div class="col-xs-4">
                            @Html.LabelFor(model => model.idDepartamento, htmlAttributes: new { @class = "control-label" })
                            @Html.DropDownListFor(model => model.idDepartamento, (SelectList)ViewBag.Departamento, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.idDepartamento, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <br />
                        <br />
                            <br />
                                <br />
                    <div class="form-group">
                        <div class="col-xs-4">
                            @Html.LabelFor(model => model.tituloItem, htmlAttributes: new { @class = "control-label" })
                            @Html.EditorFor(model => model.tituloItem, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.tituloItem, "", new { @class = "text-danger" })
                        </div>

                        <div class="col-xs-4">
                            @Html.LabelFor(model => model.dtProgramada, htmlAttributes: new { @class = "control-label" })
                            @Html.EditorFor(model => model.dtProgramada, new { htmlAttributes = new { @class = "form-control", @id= "dtProg" } })
                            @Html.ValidationMessageFor(model => model.dtProgramada, "", new { @class = "text-danger" })
                        </div>

                        <div class="col-xs-4">
                            @Html.LabelFor(model => model.idTipoDesenv, htmlAttributes: new { @class = "control-label" })
                            @Html.DropDownListFor(model => model.idTipoDesenv, (SelectList)ViewBag.TipoDesenvolvimento, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.idTipoDesenv, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <br />
                        <br />
                            <br />
                                <br />
                    <div class="form-group">                       
                        <div class="col-xs-4">
                            @Html.LabelFor(model => model.idDev, htmlAttributes: new { @class = "control-label" })
                            @Html.DropDownListFor(model => model.idDev, (SelectList)ViewBag.Desenvolvedor, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.idDev, "", new { @class = "text-danger" })
                        </div>

                        <div class="col-xs-4">
                            @Html.LabelFor(model => model.idStatus, htmlAttributes: new { @class = "control-label" })
                            @Html.DropDownListFor(model => model.idStatus, (SelectList)ViewBag.Status, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.idStatus, "", new { @class = "text-danger" })
                        </div>

                        <div class="col-xs-4">
                            @Html.LabelFor(model => model.idPrioridade, htmlAttributes: new { @class = "control-label" })
                            @Html.DropDownListFor(model => model.idPrioridade, (SelectList)ViewBag.Prioridade, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.idPrioridade, "", new { @class = "text-danger" })
                        </div> 
                    </div>
                    <br />
                        <br />
                            <br />
                                <br />
                                      <br />
                    <div class="form-group">                    
                        <div class="col-xs-4">
                            @Html.LabelFor(model => model.descicao, htmlAttributes: new { @class = "control-label" })
                            @Html.TextAreaFor(model => model.descicao, htmlAttributes: new { @class = "form-control", @rows = "22", @cols = "36", @style = "resize: none;" })
                            @Html.ValidationMessageFor(model => model.descicao, "", new { @class = "text-danger" })
                        </div> 

                        @*<div class="col-xs-6">
                            @Html.Label("Anexo", new { @class="control-label"})      
                            <br />                    
                            <span class="btn btn-dark fileinput-button">                      
                                <input type="file" id="file" name="files[]" multiple /> 
                            </span>                                                     
                        </div>*@
                    </div>
                    <div class="clearfix"></div>                     
                </form>
                <br /> 
                <br />                
                <div class="col-md-6 col-sm-6 col-xs-12 form-group has-feedback">
                    <button type="submit" class="btn btn-success">
                        <span class="glyphicon glyphicon-floppy-disk"></span> Salvar
                    </button>

                    <button type="button" onclick="location.href='@Url.Action("Index", "OsProjetos")'" class="btn btn-info">
                        <span class="glyphicon glyphicon-backward"></span> Voltar
                    </button>
                </div>
            </div>
        </div>
    </div>
}

 <!-- Modal -->
<div class="modal fade" id="modalSaveSuccess" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header modal-header-success" style="background-color: cadetblue;">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="myModalLabel" style="color: white; text-align:center">ATENÇÃO !!!</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="form-group" style="align-items:center">
                        <div class="col-xs-7">
                            <label style="padding-left: 5%;" class="control-label">@ViewBag.Mensagem</label>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                @Html.ActionLink("OK", "Index", "OsProjetos", "", new { @class="btn btn-success"})
            </div>
        </div>
    </div>
</div>
<!-- ####  // Modal // #### -->  

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<script src="https://momentjs.com/downloads/moment.min.js" type="text/javascript"></script>
<script src="https://momentjs.com/downloads/moment-with-locales.min.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js" type="text/javascript"></script>

<script type="text/javascript">

        $("#dtProg").datetimepicker(
            {
                showTodayButton: true,
                format: 'YYYY-MM-DD HH:mm',
                showClose: true,
                showClear: true,
                toolbarPlacement: 'top'
            });

        if (new String("@ViewBag.Mensagem") != ""){

            $(document).ready(function () {
                $('#modalSaveSuccess').modal('show');
            });
        }

</script>

WebApp/Views/Itens/ListaItemPorStatus.cshtml
@model IEnumerable<Model.modItensListasPorStatus>

@{
    ViewBag.Title = "Lista Itens Por Status";

    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-xs-12">
    <div class="x_panel">
        <h3>Resultado da Pesquisa</h3>
        <button type="button" onclick="location.href='@Url.Action("PesquisaItemPorStatus", "Itens")'" class="btn btn-danger" 
                style="margin-left: 86.5%; margin-top: -3%;">
            <span class="glyphicon glyphicon-backward"></span> Voltar para pesquisa
        </button>   
        <div class="x_title">
            <ul class="nav navbar-right panel_toolbox">
                <li>
                    <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <li>
                    <a class="close-link"><i class="fa fa-close"></i></a>
                </li>
            </ul>
        </div>
        <div class="x_content">
            <div id="datatable_filter" class="dataTables_filter">
            </div><table id="tablePesquisa" class="table table-responsive dataTable table-bordered table-striped"
                         role="grid" aria-describedby="datatable_info">
                      <thead>
                          <tr>
                              <th style="text-align:center">
                                  @Html.DisplayName("Projeto")
                              </th>
                              <th style="text-align:center">
                                  @Html.DisplayName("Item")
                              </th>
                              <th style="text-align:center">
                                  @Html.DisplayName("Solicitante")
                              </th>
                              <th style="text-align:center">
                                  @Html.DisplayName("Título")
                              </th>
                              <th style="text-align:center">
                                  @Html.DisplayName("Abertura")
                              </th>
                              <th style="text-align:center">
                                  @Html.DisplayName("Programado")
                              </th>
                              <th style="text-align:center">
                                  @Html.DisplayName("Status")
                              </th>
                              <th style="text-align:center">
                                  @Html.DisplayName("Desenvolvedor")
                              </th>
                              <th style="text-align:center">
                                  @Html.DisplayName("Descrição")
                              </th>
                                   <th style="text-align:center">
                              </th>                            
                          </tr>
                      </thead>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td style="color:red;">
                                @Html.DisplayFor(modelItem => item.projeto)
                            </td>
                            <td align="center">
                                @Html.DisplayFor(modelItem => item.idItem)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.solicitante)
                            </td>
                            <td align="center">
                                @Html.DisplayFor(modelItem => item.titulo)
                            </td>
                            <td align="center">
                                @Html.DisplayFor(modelItem => item.dtCadastro)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.dtProgramada)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.status)
                            </td>
                            <td align="center">
                                @Html.DisplayFor(modelItem => item.desenvolvedor)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.descricao)
                            </td>
                            <td align="center">
                                @Html.ActionLink("Ver Detalhes", "Details", "Itens", new { id = item.idItem }, new { @class = "btn btn-sm btn-warning" })
                            </td> 
                        </tr>
                    }
            </table>
        </div>    
    </div>
</div>    

WebApp/Views/Itens/PesquisaItemPorStatus.cshtml
@{
    ViewBag.Title = "Pesquisa por Status";
}

@using (Html.BeginForm())
{
<div class="row">
    <div class="x_panel">
        <h4>Pesquisa por status</h4>
        <hr />
        <div class="x_content">
            <form class="form-horizontal form-label-left input_mask form-group has-feedback">

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    <div class="col-xs-4">
                        @Html.Label("Selecione um status", htmlAttributes: new { @class = "control-label" })
                        @Html.DropDownList("id", (SelectList)ViewBag.Status, new { @class = "form-control" })
                        @Html.ValidationMessage("id", "", new { @class = "text-danger" })
                    </div>

                    <div class="col-md-6 col-sm-6 col-xs-12" style="padding-top: 3px;">
                        <br />
                        <button type="submit" class="btn btn-info">
                            <span class="glyphicon glyphicon-search"></span> Pesquisar
                        </button>

                        <button type="button" onclick="location.href='@Url.Action("Index", "Home")'" class="btn btn-dark">
                            <span class="glyphicon glyphicon-backward"></span> Voltar
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
}