WebApp/Controllers/TipoDesenvolvimentoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Model;
using Dal;

namespace WebApp.Controllers
{
    public class TipoDesenvolvimentoController : Controller
    {
        #region Lista todos os tipos de desenvolvimento cadastrados (View)
        // GET: TipoDesenvolvimento
        dalTipoDesenvolvimento _db = new dalTipoDesenvolvimento();
        public ActionResult Index()
        {
            if (Session["NomeLogin"] != null)
            {
                var model = _db.pubListaTiposDesenvolvimento();

                return View(model);
            }
            else
            {
                return RedirectToAction("Logar", "Usuario");
            }
        }
        #endregion

        // GET: TipoDesenvolvimento/Details/5
        public ActionResult Details(int id)
        {
            if (Session["NomeLogin"] != null)
            {
                var model = _db.pubTipoDesenvolvimentoPorId(id);

                return View(model);
            }
            else
            {
                return RedirectToAction("Logar", "Usuario");
            }
        }

        // GET: TipoDesenvolvimento/Create
        public ActionResult Create()
        {
            if (Session["NomeLogin"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Logar", "Usuario");
            }
        }

        // POST: TipoDesenvolvimento/Create
        [HttpPost]
        public ActionResult Create(modTipoDesenvolvimento tpDesenvolvimento)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _db.pubCadastraTipoDesenvolvimento(tpDesenvolvimento);

                    return RedirectToAction("Index");
                }
                catch
                {
                    return View(tpDesenvolvimento);
                }
            }
            return View();
            
        }

        // GET: TipoDesenvolvimento/Edit/5
        public ActionResult Edit(int id)
        {
            if (Session["NomeLogin"] != null)
            {
                var model = _db.pubTipoDesenvolvimentoPorId(id);

                return View(model);
            }
            else
            {
                return RedirectToAction("Logar", "Usuario");
            }
        }

        // POST: TipoDesenvolvimento/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, modTipoDesenvolvimento tpDesenvolvimento)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    tpDesenvolvimento.idTipoDesenvolvimento = id;

                    _db.pubAtualizaTipoDesenvolvimento(tpDesenvolvimento);

                    return RedirectToAction("Index");
                }
                catch
                {
                    return View(tpDesenvolvimento);
                }
            }

            return View();           
        }

        // GET: TipoDesenvolvimento/Delete/5
        public ActionResult Delete(int id)
        {
            if (Session["NomeLogin"] != null)
            {
                var model = _db.pubTipoDesenvolvimentoPorId(id);

                return View(model);
            }
            else
            {
                return RedirectToAction("Logar", "Usuario");
            }
        }

        // POST: TipoDesenvolvimento/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, modTipoDesenvolvimento tpDesenvolvimento)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    tpDesenvolvimento.idTipoDesenvolvimento = id;

                    _db.pubRemoveTipoDesenvolvimentoPorId(tpDesenvolvimento);

                    return RedirectToAction("Index");
                }
                catch
                {
                    return View(tpDesenvolvimento);
                }
            }

            return View();          
        }
    }
}

WebApp/Views/TipoDesenvolvimento/Create.cshtml
@model Model.modTipoDesenvolvimento

@{
    ViewBag.Title = "Cadastro tipo de desenvolvimento";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="row">
        <div class="x_panel">
            <h4>Novo tipo de desenvolvimento</h4>
            <hr />
            <div class="x_content">
                <form class="form-horizontal form-label-left input_mask form-group has-feedback">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="col-xs-4">
                        @Html.LabelFor(model => model.descricao, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.descricao, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.descricao, "", new { @class = "text-danger" })
                    </div>

                    <br />
                    <div class="col-xs-4" style="padding-top: 4px;">
                        <button type="submit" class="btn btn-success">
                            <span class="glyphicon glyphicon-floppy-disk"></span> Salvar
                        </button>

                        <button type="button" onclick="location.href='@Url.Action("Index", "TipoDesenvolvimento")'" class="btn btn-warning">
                            <span class="glyphicon glyphicon-backward"></span> Voltar
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
}

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

WebApp/Views/TipoDesenvolvimento/Delete.cshtml
@model Model.modTipoDesenvolvimento

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="x_panel">
        <h4>Remover Departamento</h4>
        <hr />
        <div class="x_content">
            <dl class="form-horizontal form-label-left input_mask form-group has-feedback col-xs-4">            

                <dt>
                    @Html.DisplayNameFor(model => model.descricao)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.descricao)
                </dd>

            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <br />
                <div class="col-xs-4">
                    <button type="submit" class="btn btn-danger">
                        <span class="glyphicon glyphicon-trash"></span> Remover
                    </button>

                    <button type="button" onclick="location.href='@Url.Action("Index", "TipoDesenvolvimento")'" class="btn btn-info">
                        <span class="glyphicon glyphicon-backward"></span> Voltar
                    </button>
                </div>
            }
        </div>
    </div>
</div>

WebApp/Views/TipoDesenvolvimento/Edit.cshtml
@model Model.modTipoDesenvolvimento

@{
    ViewBag.Title = "Alterar tipo de desenvolvimento";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="row">
        <div class="x_panel">
            <h4>Alterar tipo de desenvolvimento</h4>
            <hr />
            <div class="x_content">
                <form class="form-horizontal form-label-left input_mask form-group has-feedback">

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="form-group">
                        @Html.LabelFor(model => model.descricao, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.descricao, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.descricao, "", new { @class = "text-danger" })
                    </div>

                    <br />
                    <div class="col-xs-4" style="padding-top: 4px;">
                        <button type="submit" class="btn btn-dark">
                            <span class="glyphicon glyphicon-edit"></span> Salvar
                        </button>

                        <button type="button" onclick="location.href='@Url.Action("Index", "TipoDesenvolvimento")'" class="btn btn-info">
                            <span class="glyphicon glyphicon-backward"></span> Voltar
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
}

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

WebApp/Views/TipoDesenvolvimento/Index.cshtml
@model IEnumerable<Model.modTipoDesenvolvimento>

@{
    ViewBag.Title = "Lista tipos de desenvolvimento";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
        <h3>Lista tipos de desenvolvimento - <small>cadastros</small></h3>
        <div class="x_title">
            <ul class="nav navbar-right panel_toolbox">
                <li>
                    <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <li>
                    <a class="close-link"><i class="fa fa-close"></i></a>
                </li>
            </ul>
        </div>
        <div class="x_content">
            <div id="datatable_filter" class="dataTables_filter">
            </div><table id="datatableUser" class="table table-striped table-bordered dataTable no-footer dtr-inline"
                         role="grid" aria-describedby="datatable_info">

                <thead>
                    <tr>                  
                        <th>
                            @Html.DisplayNameFor(model => model.descricao)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                @foreach (var item in Model)
                {
                    <tr>                      
                        <td>
                            @Html.DisplayFor(modelItem => item.descricao)
                        </td>
                        <td align="center">
                            <div class="btn-group">
                                @Html.ActionLink("Editar", "Edit", new { id = item.idTipoDesenvolvimento }, new { @class = "btn btn-sm btn-info" })
                                @Html.ActionLink("Remover", "Delete", new { id = item.idTipoDesenvolvimento }, new { @class = "btn btn-sm btn-danger" })
                            </div>
                        </td>
                    </tr>
                }

            </table>
        </div>
    </div>
</div>