WebApp/Controllers/DesenvolvedoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Model;
using Dal;

namespace WebApp.Controllers
{
    public class DesenvolvedoresController : Controller
    {
        // GET: Desenvolvedores
        dalDesenvolvedores _db = new dalDesenvolvedores();
        public ActionResult Index()
        {
            if (Session["NomeLogin"] != null)
            {
                if (ModelState.IsValid)
                {
                    var model = _db.pubListaDesenvolvedores();

                    return View(model);
                }

                return View();
            }
            else
            {
                return RedirectToAction("Logar", "Usuario");
            }
        }

        // GET: Desenvolvedores/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Desenvolvedores/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Desenvolvedores/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Desenvolvedores/Edit/5
        public ActionResult Edit(int id)
        {
            if (Session["NomeLogin"] != null)
            {
                var model = _db.pubBuscaDesenvolvedorPorId(id);

                return View(model);
            }
            else
            {
                return RedirectToAction("Logar", "Usuario");
            }
        }

        // POST: Desenvolvedores/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, modDesenvolvedores dev)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    dev.idDev = id;
                    
                    return RedirectToAction("Index");
                }
                catch
                {
                    return View(dev);
                }
            }

            return View();
            
        }

        // GET: Desenvolvedores/Delete/5
        public ActionResult Delete(int id)
        {
            var model = _db.pubBuscaDesenvolvedorPorId(id);

            return View(model);
        }

        // POST: Desenvolvedores/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, modDesenvolvedores dev)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    dev.idDev = id;
                    _db.pubRemoveDesenvolvedor(dev);

                    return RedirectToAction("Index");
                }
                catch
                {
                    return View();
                }
            }
            return View();
        }
    }
}

WebApp/Views/Desenvolvedores/Delete.cshtml
@model Model.modDesenvolvedores

@{
    ViewBag.Title = "Editar desenvolvedor";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="row">
        <div class="x_panel">
            <h4>Remover desenvolvedor</h4>
            <hr />
            <div class="x_content">
                <form class="form-horizontal form-label-left input_mask form-group has-feedback">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="col-xs-4">
                        @Html.LabelFor(model => model.nomeCompleto, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.nomeCompleto, new { htmlAttributes = new { @class = "form-control", @disabled= "disabled" } })
                        @Html.ValidationMessageFor(model => model.nomeCompleto, "", new { @class = "text-danger" })
                    </div>
                    <br />
                    <div class="col-xs-4" style="padding-top: 4px;">
                        <button type="submit" class="btn btn-dark">
                            <span class="glyphicon glyphicon-edit"></span> Remover
                        </button>

                        <button type="button" onclick="location.href='@Url.Action("Index", "Desenvolvedores")'" class="btn btn-warning">
                            <span class="glyphicon glyphicon-backward"></span> Voltar
                        </button>
                    </div>  
                </form>
            </div>
        </div>
    </div>
}

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

WebApp/Views/Desenvolvedores/Index.cshtml
@model IEnumerable<Model.modDesenvolvedores>

@{
    ViewBag.Title = "Lista Desenvolvedores";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
        <h3>Lista desenvolvedores - <small>cadastros</small></h3>
        <div class="x_title">
            <ul class="nav navbar-right panel_toolbox">
                <li>
                    <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <li>
                    <a class="close-link"><i class="fa fa-close"></i></a>
                </li>
            </ul>
        </div>
        <div class="x_content">
            <div id="datatable_filter" class="dataTables_filter">
            </div><table id="datatableUser" class="table table-striped table-bordered dataTable no-footer dtr-inline"
                         role="grid" aria-describedby="datatable_info">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.idDev)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.idUsuario)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.nomeCompleto)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.idDev)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.idUsuario)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.nomeCompleto)
                        </td>
                        <td align="center">
                            @Html.ActionLink("Remover", "Delete", new { id = item.idDev }, new { @class = "btn btn-sm btn-warning" })
                        </td>
                    </tr>
                }

            </table>
        </div>
    </div>
</div>